name: Build kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Init the System
         uses: actions/checkout@master

       - name: Download necessary tools
         run: |
             sudo apt update -y
             sudo apt install bc zip make tar libncurses* gcc clang python3 -y
