name: Build kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Init the System
         uses: actions/checkout@master

       - name: Download Necessary Packages
         run: |
             sudo apt update -y
             sudo apt install bc git zip make tar libncurses* gcc clang python3 openssl util-linux perl binutils e2fsprogs udev build-essential bison flex libssl-dev libelf-dev p7zip  -y

       - name: Download Kernel Source
         run: |
             source config.sh
             git clone --depth=1 $KERNEL_SOURCE -b $SOURCE_BRANCH work

       - name: Download Toolchain
         run: |
             source config.sh
             wget -qO - https://github.com/bread-up/kernel_builder/raw/main/scripts/setuptoolchain.sh | bash

       - name: Make Defconfig
         run: |
             source config.sh
             cd work
             make $DEFCONFIG

       - name: Compile Kernel
         run: |
             source config.sh
             cd work
             wget -qO - https://github.com/bread-up/kernel_builder/raw/main/scripts/compilekernel.sh | bash

       - name: Make a zip
         run: |
             source config.sh
             cd work
             wget -qO - https://github.com/bread-up/kernel_builder/raw/main/scripts/makezip.sh | bash

       - name: Release kernel
         uses: softprops/action-gh-release@v1
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
          tag_name: ${{ github.run_id }}
          name: release kernel
          files: kernel.zip
